### PR TITLE
Stream-K Batch

### PR DESCRIPTION
**Pull request by AlexBrownAMD**
Batch support for stream-k kernels.
Added some new test cases. 
Small fix for rocBLAS liblogic converter script to work with old liblogic files that don't have xf32 parameter listed.

### CODE REVIEW

**Comment by nakajee** [comment]
Does this work with non strided batched cases?

**Comment by nakajee** [comment]
Would you create a separate PR for the new tool?
Also, please put some brief comment about how to use it.

**Comment by AlexBrownAMD** [comment]
> Does this work with non strided batched cases?

General batch is not supported, just strided batch or non-batch

**Comment by nakajee** [comment]
> > Does this work with non strided batched cases?
> 
> General batch is not supported, just strided batch or non-batch

In that case, I think it is better to add a reject condition for general batch case.

**Comment by AlexBrownAMD** [comment]
> Would you create a separate PR for the new tool? Also, please put some brief comment about how to use it.

tuning scripts moved to PR 1865

**Comment by AlexBrownAMD** [comment]
> > > Does this work with non strided batched cases?
> > 
> > 
> > General batch is not supported, just strided batch or non-batch
> 
> In that case, I think it is better to add a reject condition for general batch case.

Added reject condition

**Comment by nakajee** [comment]
The code change looks OK.
Do you know why extended CI is not triggered?
I would like to make sure the test cases you added passes.

**Comment by AlexBrownAMD** [comment]
> The code change looks OK. Do you know why extended CI is not triggered? I would like to make sure the test cases you added passes.

Not sure why it didn't start auomtaically - just started a run manually.

**Review by nakajee — APPROVED** [review]
Looks good.

**Pull request merged**
