### PR TITLE
Add gfx1151 support

### PR DESCRIPTION
**Pull request by amd-garydeng**
resolves #___

**Summary:**

enable gfx1151 support

*What is being changed and why?

**Outcomes:**

*What is the result of this change? What components of the project does it affect?*

**Notable changes:**

*Are there any changes that are of particular importance*?

**Testing and Environment:**

*What environment are you targeting (OS, ROCm version, Python versions, etc.)?*

*What testing did you do to ensure this change will integrate successfully?

### CODE REVIEW

**Review by yoichiyoshida — APPROVED** [review]
lgtm

**Comment by nakajee** [comment]
I think you need to add skip-gfx1151 to all yaml files under Tensile/Tests with skip-gfx1100.

**Comment by nakajee** [comment]
Please run precheckin + extended tests.

**Comment by nakajee** [comment]
I grepped "gfx1100" in Tensile and found some hits under Tensile\Source\lib.
Don't we need to add gfx1151 to these files?

**Comment by nakajee** [comment]
I grepped (11,
In Common.py
  isasWithDisabledHWMonitor = ((9,4,1), (9,4,2), (11,0,0), (11,0,1), (11,0,2), (12,0,0), (12,0,1))
Do we need to disable HW monitor for 1151?

**Comment by eidenyoshida** [comment]
@yoichiyoshida  can you answer @nakajee 's questions?

**Comment by yoichiyoshida** [comment]
we're only adding hip fallback support for this arch, we are not running any assembly tests

**Pull request merged**
