### PR TITLE
Add defineLocalSgpr

### PR DESCRIPTION
**Pull request by awhittle3**
Added a new method to manage SGPR usage: defineLocalSgpr. This allows in-place defining/undefing of SGPRs.

Also added new parameter `PrintRegisterDebug` that informs the invoker if SGPRs have not been explicitly undefined, as a optimization hint.

The old defineSgpr function still works as expected and is in place elsewhere in the code.

### CODE REVIEW

**Comment by nakajee** [comment]
CI tests failed due to incorrect asm code.
Please fix them.

**Comment by awhittle3** [comment]
> @awhittle3 Some CI tests failed, do we still need this change?

This PR will conflict with PR #1843, which probably has higher priority. I'll address the issues here once that PR is merged into `develop`.

@AlexBrownAMD believes this change will be helpful in managing SGPR usage.

**Comment by nakajee** [comment]
> > @awhittle3 Some CI tests failed, do we still need this change?
> 
> This PR will conflict with PR #1843, which probably has higher priority. I'll address the issues here once that PR is merged into `develop`.
> 
> @AlexBrownAMD believes this change will be helpful in managing SGPR usage.

#1843 is merged today. Would you please restart this PR?

**Comment by babakpst** [comment]
@awhittle3 we are approaching FC 6.2 and we want to clear all the requests. Please let me know if you are planning to proceed with this PR. Thanks.

**Comment by awhittle3** [comment]
Out of date and would take a while to spin back up. Closing work on this for now.

**Pull request closed without merging**
